#! /bin/sh

### BEGIN INIT INFO
# Provides:					 nginx
# Required-Start:		 $all
# Required-Stop:		 $all
# Default-Start:		 2 3 4 5
# Default-Stop:			 0 1 6
# Short-Description: starts the nginx web server
# Description:			 starts nginx using start-stop-daemon
### END INIT INFO

PATH=/opt/nginx/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/opt/nginx/sbin/nginx
NAME=nginx
DESC=nginx

test -x $DAEMON || exit 0

# Include nginx defaults if available
if [ -f /etc/default/nginx ] ; then
	. /etc/default/nginx
fi

set -e

test_config() {
		echo 'Checking config...'
		set +e
		RES=`nginx -t 2>&1`
		if [ $? -ne 0 ] ; then
				echo "Error in nginx configuration found!"
				echo $RES
				exit 10
		fi
		set -e
		echo "All good."
}

case "$1" in
	start)
	echo -n "Starting $DESC: "
	start-stop-daemon --start --quiet --pidfile /opt/nginx/logs/$NAME.pid --exec $DAEMON -- $DAEMON_OPTS || true
	echo "$NAME started."
	;;
	stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon --stop --quiet --pidfile /opt/nginx/logs/$NAME.pid --exec $DAEMON || true
	echo "$NAME stopped."
	;;
	restart|force-reload)
		test_config
	echo -n "Restarting $DESC: "
	start-stop-daemon --stop --quiet --pidfile \
		/opt/nginx/logs/$NAME.pid --exec $DAEMON || true
	sleep 1
	start-stop-daemon --start --quiet --pidfile \
		/opt/nginx/logs/$NAME.pid --exec $DAEMON -- $DAEMON_OPTS || true
	echo "$NAME restarted."
	;;
	reload)
		test_config
		echo -n "Reloading $DESC configuration: "
		start-stop-daemon --stop --signal HUP --quiet --pidfile /opt/nginx/logs/$NAME.pid \
				--exec $DAEMON || true
		echo "$NAME reloaded."
		;;
	configtest)
		test_config
		;;
	*)
	echo "Usage: $NAME {start|stop|restart|reload|force-reload|configtest}" >&2
	exit 1
	;;
esac

exit 0